# [교육] 온라인 강의 사용자 로그 분석 및 시각화
- 사용자 로그로 온라인 강의의 ‘참여’와 ‘이탈’을 어떻게 읽을 것인가?

- 온라인 강의 데이터 기반 대시보드 구축 프로젝트
    - 학습자 참여도 진단 → 이탈 구간 발견 → 개선 방향 제시

### 주제 목표
- 사용자 로그 기반 온라인 강의 학생참여도 진단 및 수료율 개선안 제시

- 학습자 행동 로그를 기반으로 다양한 지표를 모니터링

    - 등록자는 많지만 실제 학습 시작자는 충분한가?
    - 시작한 학생들은 꾸준히 학습하는가?
    - 영상 시청, 챕터 탐색, 포럼 참여 같은 행동은 수료와 어떤 관련이 있는가?
    - 특정 코스나 특정 학습자 집단에서 이탈이 더 심한가?

In [147]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import matplotlib.pyplot as plt
import platform
import os
import glob

plt.rcParams['font.family'] = 'Malgun Gothic'

In [148]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import scipy as stats
# import seaborn as sns
# import numpy as np

# 출력 짤림 방지
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [149]:
# 데이터 불러오기
df = pd.read_csv('./data/Courses.csv', parse_dates=['start_time_DI', 'last_event_DI'])
df.head()

,index,course_id,userid_DI,registered,viewed,explored,certified,final_cc_cname_DI,LoE_DI,YoB,gender,grade,start_time_DI,last_event_DI,nevents,ndays_act,nplay_video,nchapters,nforum_posts,roles,incomplete_flag
0,0,HarvardX/CB22x/2013_Spring,MHxPC130442623,1,0,0,0,United States,NaN,NaN,NaN,0,2012-12-19,2013-11-17,NaN,9.0,NaN,NaN,0,NaN,1.0
1,1,HarvardX/CS50x/2012,MHxPC130442623,1,1,0,0,United States,NaN,NaN,NaN,0,2012-10-15,NaT,NaN,9.0,NaN,1.0,0,NaN,1.0
2,2,HarvardX/CB22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2013-02-08,2013-11-17,NaN,16.0,NaN,NaN,0,NaN,1.0
3,3,HarvardX/CS50x/2012,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2012-09-17,NaT,NaN,16.0,NaN,NaN,0,NaN,1.0
4,4,HarvardX/ER22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2012-12-19,NaT,NaN,16.0,NaN,NaN,0,NaN,1.0

In [150]:
# df = pd.read_csv("data/Courses.csv")

In [151]:
# 원본데이터 결측치 개수, 비율
display(pd.DataFrame({
    'sum': df.isna().sum(),
    'ratio': df.isna().mean() * 100
}).sort_values('ratio', ascending=False).reset_index())

                index     sum       ratio
0               roles  641138  100.000000
1     incomplete_flag  540977   84.377622
2         nplay_video  457530   71.362172
3           nchapters  258753   40.358394
4             nevents  199151   31.062111
5       last_event_DI  178954   27.911932
6           ndays_act  162743   25.383459
7              LoE_DI  106008   16.534350
8                 YoB   96605   15.067739
9              gender   86806   13.539363
10              grade   48372    7.544710
11              index       0    0.000000
12          course_id       0    0.000000
13             viewed       0    0.000000
14         registered       0    0.000000
15          userid_DI       0    0.000000
16  final_cc_cname_DI       0    0.000000
17      start_time_DI       0    0.000000
18           explored       0    0.000000
19          certified       0    0.000000
20       nforum_posts       0    0.000000

In [152]:
# 전처리용 데이터 셋 생성
pre = df.copy()

In [153]:
# 중복행 확인
len(pre.duplicated())
pre.duplicated().sum()

np.int64(0)

In [154]:
# 의미없는 컬럼 제거
pre = pre.drop(columns=['index', 'roles'])

# 데이터 확인

In [155]:
pre.head()

,course_id,userid_DI,registered,viewed,explored,certified,final_cc_cname_DI,LoE_DI,YoB,gender,grade,start_time_DI,last_event_DI,nevents,ndays_act,nplay_video,nchapters,nforum_posts,incomplete_flag
0,HarvardX/CB22x/2013_Spring,MHxPC130442623,1,0,0,0,United States,NaN,NaN,NaN,0,2012-12-19,2013-11-17,NaN,9.0,NaN,NaN,0,1.0
1,HarvardX/CS50x/2012,MHxPC130442623,1,1,0,0,United States,NaN,NaN,NaN,0,2012-10-15,NaT,NaN,9.0,NaN,1.0,0,1.0
2,HarvardX/CB22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2013-02-08,2013-11-17,NaN,16.0,NaN,NaN,0,1.0
3,HarvardX/CS50x/2012,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2012-09-17,NaT,NaN,16.0,NaN,NaN,0,1.0
4,HarvardX/ER22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2012-12-19,NaT,NaN,16.0,NaN,NaN,0,1.0

In [156]:
pre.shape

(641138, 19)

In [157]:
pre.info()

<class 'pandas.DataFrame'>
RangeIndex: 641138 entries, 0 to 641137
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   course_id          641138 non-null  str
 1   userid_DI          641138 non-null  str
 2   registered         641138 non-null  int64
 3   viewed             641138 non-null  int64
 4   explored           641138 non-null  int64
 5   certified          641138 non-null  int64
 6   final_cc_cname_DI  641138 non-null  str
 7   LoE_DI             535130 non-null  str
 8   YoB                544533 non-null  float64
 9   gender             554332 non-null  str
 10  grade              592766 non-null  str
 11  start_time_DI      641138 non-null  datetime64[us]
 12  last_event_DI      462184 non-null  datetime64[us]
 13  nevents            441987 non-null  float64
 14  ndays_act          478395 non-null  float64
 15  nplay_video        183608 non-null  float64
 16  nchapters          382385 non-null  float64
 17  nforum_posts       641138 non-null  int64
 18  incomplete_flag    100161 non-null  float64
dtypes: datetime64[us](2), float64(6), int64(5), str(6)
memory usage: 92.9 MB

In [158]:
pre.isna().sum()

course_id                 0
userid_DI                 0
registered                0
viewed                    0
explored                  0
certified                 0
final_cc_cname_DI         0
LoE_DI               106008
YoB                   96605
gender                86806
grade                 48372
start_time_DI             0
last_event_DI        178954
nevents              199151
ndays_act            162743
nplay_video          457530
nchapters            258753
nforum_posts              0
incomplete_flag      540977
dtype: int64

# 주제 확인

### 중요 컬럼명
- **registered**: 강의 등록 여부
- **viewed**: 강의를 실제로 열어본 적이 있는지
- **explored**: 강의 콘텐츠를 더 깊게 탐색했는지
- **certified**: 최종적으로 인증서를 획득했는지
- **grade**: 학습 성취 수준
- **nevents**: 전체 학습 이벤트 수
- **ndays_act**: 실제 활동한 일수
- **nplay_video**: 영상 재생 수
- **nchapters**: 탐색한 챕터 수
- **nforum_posts**: 포럼 활동량


-> 학습자의 행동을 다음과 같은 퍼널로 해석할 수 있다

    - 등록 → 첫 방문 → 적극적 탐색 → 지속 학습 → 인증/수료

### 핵심 질문
- 우리 플랫폼의 전체 학습 퍼널은 어떻게 생겼는가?
- 학생들은 **어느 단계에서 가장 많이 이탈**하는가?
- **참여도가 높은 학생과 낮은 학생**은 어떤 행동 차이를 보이는가?
- 어떤 코스가 상대적으로 **참여 유지율 / 인증 전환율**이 높은가?
- 국가, 성별, 학력, 연령대 같은 특성에 따라 차이가 보이는가?
- 영상 재생 수, 활동일수, 챕터 탐색 수, 포럼 활동은 성취도나 인증과 어떤 관련이 있는가?
- 우리 서비스가 학생참여도를 높이기 위해 우선적으로 개선해야 할 지점은 무엇인가?

### 대시보드 작성 프로세스
- 분석 기획 완료 후 분석 주제 세분화
    - 학습자 관점 / 코스 관점 / 퍼널 관점
- 각 주제별로 어떤 질문에 답할지 정의
- 노트에 먼저 손으로 스케치
    - KPI 카드 위치
    - 필터 위치
    - 차트 간 연결 흐름
    - 사용자가 어떤 순서로 읽을지
- 스케치 후 워크시트 제작을 진행
- 제작 중 가시성이 떨어지거나 메시지가 약하면 과감히 수정

# 데이터 딕셔너리

In [159]:
display(pre.describe(include='all').T)

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
course_id,641138,16,HarvardX/CS50x/2012,169621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userid_DI,641138,476532,MHxPC130505428,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
registered,641138.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0
viewed,641138.0,NaN,NaN,NaN,0.624299,0.0,0.0,1.0,1.0,1.0,0.484304
explored,641138.0,NaN,NaN,NaN,0.061899,0.0,0.0,0.0,0.0,1.0,0.240973
certified,641138.0,NaN,NaN,NaN,0.027587,0.0,0.0,0.0,0.0,1.0,0.163786
final_cc_cname_DI,641138,34,United States,184240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LoE_DI,535130,5,Bachelor's,219768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YoB,544533.0,NaN,NaN,NaN,1985.253279,1931.0,1982.0,1988.0,1991.0,2013.0,8.891814
gender,554332,3,m,411520,NaN,NaN,NaN,NaN,NaN,NaN,NaN
grade,592766,104,0,490868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_time_DI,641138,NaN,NaN,NaN,2013-01-02 16:07:19.273916,2012-07-23 00:00:00,2012-10-01 00:00:00,2013-01-10 00:00:00,2013-03-10 00:00:00,2013-09-08 00:00:00,NaN
last_event_DI,462184,NaN,NaN,NaN,2013-03-11 02:44:13.343257,2012-07-24 00:00:00,2012-12-25 00:00:00,2013-03-17 00:00:00,2013-05-29 00:00:00,2013-11-17 00:00:00,NaN
nevents,441987.0,NaN,NaN,NaN,431.008018,1.0,3.0,24.0,158.0,197757.0,1516.116057
ndays_act,478395.0,NaN,NaN,NaN,5.710254,1.0,1.0,2.0,4.0,205.0,11.866471
nplay_video,183608.0,NaN,NaN,NaN,114.844173,1.0,5.0,18.0,73.0,98517.0,426.996844
nchapters,382385.0,NaN,NaN,NaN,3.634423,1.0,1.0,2.0,4.0,48.0,4.490987
nforum_posts,641138.0,NaN,NaN,NaN,0.018968,0.0,0.0,0.0,0.0,20.0,0.229539
incomplete_flag,100161.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0

In [160]:
pre[['incomplete_flag']].value_counts()

incomplete_flag
1.0                100161
Name: count, dtype: int64

In [161]:
print(pre['incomplete_flag'].dtypes)
print(pre['incomplete_flag'].isnull().sum())
print((pre['incomplete_flag'].isnull().mean() * 100).round(2))
print((pre['incomplete_flag'].isnull().mean() * 100))

float64
540977
84.38
84.37762229036494

# 주제 확인

### 중요 컬럼명
- **registered**: 강의 등록 여부
- **viewed**: 강의를 실제로 열어본 적이 있는지
- **explored**: 강의 콘텐츠를 더 깊게 탐색했는지
- **certified**: 최종적으로 인증서를 획득했는지
- **grade**: 학습 성취 수준
- **nevents**: 전체 학습 이벤트 수
- **ndays_act**: 실제 활동한 일수
- **nplay_video**: 영상 재생 수
- **nchapters**: 탐색한 챕터 수
- **nforum_posts**: 포럼 활동량


-> 학습자의 행동을 다음과 같은 퍼널로 해석할 수 있다

    - 등록 → 첫 방문 → 적극적 탐색 → 지속 학습 → 인증/수료

### 핵심 질문
- 우리 플랫폼의 전체 학습 퍼널은 어떻게 생겼는가?
- 학생들은 **어느 단계에서 가장 많이 이탈**하는가?
- **참여도가 높은 학생과 낮은 학생**은 어떤 행동 차이를 보이는가?
- 어떤 코스가 상대적으로 **참여 유지율 / 인증 전환율**이 높은가?
- 국가, 성별, 학력, 연령대 같은 특성에 따라 차이가 보이는가?
- 영상 재생 수, 활동일수, 챕터 탐색 수, 포럼 활동은 성취도나 인증과 어떤 관련이 있는가?
- 우리 서비스가 학생참여도를 높이기 위해 우선적으로 개선해야 할 지점은 무엇인가?

### 대시보드 작성 프로세스
- 분석 기획 완료 후 분석 주제 세분화
    - 학습자 관점 / 코스 관점 / 퍼널 관점
- 각 주제별로 어떤 질문에 답할지 정의
- 노트에 먼저 손으로 스케치
    - KPI 카드 위치
    - 필터 위치
    - 차트 간 연결 흐름
    - 사용자가 어떤 순서로 읽을지
- 스케치 후 워크시트 제작을 진행
- 제작 중 가시성이 떨어지거나 메시지가 약하면 과감히 수정

# 데이터 딕셔너리

In [162]:
display(df.describe(include='all').T)

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
index,641138.0,NaN,NaN,NaN,320568.5,0.0,160284.25,320568.5,480852.75,641137.0,185080.742781
course_id,641138,16,HarvardX/CS50x/2012,169621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userid_DI,641138,476532,MHxPC130505428,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
registered,641138.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0
viewed,641138.0,NaN,NaN,NaN,0.624299,0.0,0.0,1.0,1.0,1.0,0.484304
explored,641138.0,NaN,NaN,NaN,0.061899,0.0,0.0,0.0,0.0,1.0,0.240973
certified,641138.0,NaN,NaN,NaN,0.027587,0.0,0.0,0.0,0.0,1.0,0.163786
final_cc_cname_DI,641138,34,United States,184240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LoE_DI,535130,5,Bachelor's,219768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YoB,544533.0,NaN,NaN,NaN,1985.253279,1931.0,1982.0,1988.0,1991.0,2013.0,8.891814
gender,554332,3,m,411520,NaN,NaN,NaN,NaN,NaN,NaN,NaN
grade,592766,104,0,490868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_time_DI,641138,NaN,NaN,NaN,2013-01-02 16:07:19.273916,2012-07-23 00:00:00,2012-10-01 00:00:00,2013-01-10 00:00:00,2013-03-10 00:00:00,2013-09-08 00:00:00,NaN
last_event_DI,462184,NaN,NaN,NaN,2013-03-11 02:44:13.343257,2012-07-24 00:00:00,2012-12-25 00:00:00,2013-03-17 00:00:00,2013-05-29 00:00:00,2013-11-17 00:00:00,NaN
nevents,441987.0,NaN,NaN,NaN,431.008018,1.0,3.0,24.0,158.0,197757.0,1516.116057
ndays_act,478395.0,NaN,NaN,NaN,5.710254,1.0,1.0,2.0,4.0,205.0,11.866471
nplay_video,183608.0,NaN,NaN,NaN,114.844173,1.0,5.0,18.0,73.0,98517.0,426.996844
nchapters,382385.0,NaN,NaN,NaN,3.634423,1.0,1.0,2.0,4.0,48.0,4.490987
nforum_posts,641138.0,NaN,NaN,NaN,0.018968,0.0,0.0,0.0,0.0,20.0,0.229539
roles,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incomplete_flag,100161.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0

In [163]:
df[['incomplete_flag']].value_counts()

incomplete_flag
1.0                100161
Name: count, dtype: int64

In [164]:
print(df['incomplete_flag'].dtypes)
print(df['incomplete_flag'].isnull().sum())
print((df['incomplete_flag'].isnull().mean() * 100).round(2))
print((df['incomplete_flag'].isnull().mean() * 100))

float64
540977
84.38
84.37762229036494

# 전처리 통합

In [165]:
### 결측치 대체 & 행 제거

In [166]:
# course_id 이상치 
    # 확인 후 이상치의 공통점 찾아서 처리여부 파악 (직접 찍어보고 확인)
    
pre[['course_code', 'course', 'course_year']] = pre['course_id'].str.split('/', expand=True) # expand=True df로 반환(열로세우기)

# CS50x는 분류 상 '상시 강의' / '기간 강의' 중 본 프로젝트의 목표에 맞지 않는 분류라 분석에 사용하지 않기로 결정
pre = pre[~pre['course_id'].str.contains('CS50x')].copy()   #~로 아닌 애들만 ㄱㄱ

print(pre['course'].value_counts())

print(pre['course_year'].value_counts())

course
6.00x     124446
6.002x     63046
ER22x      57406
PH207x     41592
PH278x     39602
8.02x      31048
CB22x      30002
14.73x     27870
7.00x      21009
3.091x     20354
8.MReV      9477
2.01x       5665
Name: count, dtype: int64
course_year
2013_Spring    298691
2012_Fall      163349
2013_Summer      9477
Name: count, dtype: int64

In [167]:
# 나라 컬럼명 변경
pre = pre.rename(columns={'final_cc_cname_DI':'country'})

In [168]:
print(pre['nevents'].value_counts().sort_index())
print(pre['ndays_act'].value_counts().sort_index())
print(pre['nchapters'].value_counts().sort_index())

nevents
1.0         56670
2.0         30867
3.0         15397
4.0          9808
5.0          7478
6.0          6374
7.0          5533
8.0          5038
9.0          4748
10.0         4372
11.0         4113
12.0         3818
13.0         3571
14.0         3360
15.0         3160
16.0         3084
17.0         2851
18.0         2734
19.0         2614
20.0         2554
21.0         2433
22.0         2311
23.0         2201
24.0         2181
25.0         2047
26.0         2016
27.0         1882
28.0         1836
29.0         1803
30.0         1768
31.0         1654
32.0         1569
33.0         1620
34.0         1528
35.0         1531
36.0         1471
37.0         1464
38.0         1390
39.0         1350
40.0         1306
41.0         1302
42.0         1223
43.0         1262
44.0         1151
45.0         1175
46.0         1151
47.0         1081
48.0         1099
49.0         1029
50.0         1072
51.0         1021
52.0         1034
53.0          988
54.0          956
55.0          958
56.0          928
57.0          940
58.0          921
59.0          879
60.0          864
61.0          911
62.0          825
63.0          833
64.0          841
65.0          838
66.0          752
67.0          760
68.0          731
69.0          773
70.0          780
71.0          768
72.0          730
73.0          710
74.0          738
75.0          739
76.0          709
77.0          678
78.0          650
79.0          661
80.0          698
81.0          624
82.0          656
83.0          682
84.0          606
85.0          603
86.0          611
87.0          614
88.0          610
89.0          576
90.0          640
91.0          565
92.0          627
93.0          611
94.0          630
95.0          559
96.0          595
97.0          547
98.0          560
99.0          536
100.0         532
101.0         572
102.0         529
103.0         487
104.0         502
105.0         542
106.0         492
107.0         494
108.0         502
109.0         488
110.0         489
111.0         483
112.0         455
113.0         437
114.0         457
115.0         454
116.0         443
117.0         446
118.0         454
119.0         425
120.0         462
121.0         391
122.0         429
123.0         418
124.0         429
125.0         419
126.0         411
127.0         388
128.0         411
129.0         426
130.0         408
131.0         381
132.0         384
133.0         350
134.0         376
135.0         377
136.0         385
137.0         362
138.0         372
139.0         347
140.0         327
141.0         404
142.0         378
143.0         334
144.0         348
145.0         335
146.0         373
147.0         359
148.0         339
149.0         330
150.0         355
151.0         331
152.0         338
153.0         329
154.0         354
155.0         313
156.0         301
157.0         305
158.0         312
159.0         322
160.0         312
161.0         314
162.0         294
163.0         285
164.0         300
165.0         302
166.0         277
167.0         298
168.0         286
169.0         281
170.0         264
171.0         268
172.0         281
173.0         278
174.0         259
175.0         291
176.0         243
177.0         284
178.0         259
179.0         268
180.0         252
181.0         268
182.0         237
183.0         266
184.0         252
185.0         256
186.0         222
187.0         231
188.0         262
189.0         229
190.0         227
191.0         236
192.0         264
193.0         265
194.0         228
195.0         259
196.0         246
197.0         246
198.0         213
199.0         229
200.0         225
201.0         245
202.0         250
203.0         244
204.0         194
205.0         219
206.0         221
207.0         236
208.0         218
209.0         210
210.0         220
211.0         220
212.0         209
213.0         218
214.0         224
215.0         223
216.0         211
217.0         194
218.0         229
219.0         206
220.0         190
221.0         218
222.0         196
223.0         211
224.0         177
225.0         209
226.0         202
227.0         207
228.0         189
229.0         186
230.0         181
231.0         197
232.0         188
233.0         206
234.0         182
235.0         193
236.0         194
237.0         178
238.0         189
239.0         212
240.0         182
241.0         183
242.0         175
243.0         184
244.0         171
245.0         177
246.0         173
247.0         181
248.0         176
249.0         169
250.0         185
251.0         190
252.0         163
253.0         167
254.0         151
255.0         167
256.0         153
257.0         181
258.0         161
259.0         164
260.0         152
261.0         151
262.0         163
263.0         155
264.0         166
265.0         174
266.0         147
267.0         173
268.0         164
269.0         163
270.0         154
271.0         167
272.0         145
273.0         165
274.0         147
275.0         142
276.0         152
277.0         165
278.0         164
279.0         146
280.0         158
281.0         154
282.0         144
283.0         140
284.0         130
285.0         154
286.0         144
287.0         145
288.0         134
289.0         135
290.0         152
291.0         174
292.0         127
293.0         153
294.0         128
295.0         142
296.0         149
297.0         134
298.0         135
299.0         134
300.0         130
301.0         158
302.0         138
303.0         145
304.0         117
305.0         112
306.0         132
307.0         130
308.0         137
309.0         149
310.0         133
311.0         120
312.0         134
313.0         135
314.0         108
315.0         131
316.0         143
317.0         142
318.0         128
319.0         121
320.0         107
321.0         125
322.0         130
323.0         114
324.0         132
325.0         126
326.0         122
327.0         123
328.0         115
329.0         110
330.0         137
331.0         104
332.0         109
333.0         122
334.0          98
335.0         109
336.0         108
337.0         122
338.0         125
339.0         126
340.0         116
341.0         106
342.0         109
343.0         108
344.0         126
345.0         106
346.0         116
347.0         113
348.0          96
349.0         108
350.0         108
351.0         132
352.0         119
353.0          97
354.0         117
355.0         116
356.0         108
357.0         118
358.0         103
359.0         100
360.0         108
361.0          98
362.0          98
363.0          96
364.0          96
365.0         106
366.0         105
367.0          95
368.0         104
369.0          95
370.0          95
371.0          95
372.0         110
373.0         107
374.0          99
375.0         100
376.0          95
377.0         117
378.0         103
379.0          91
380.0         108
381.0          99
382.0          96
383.0          96
384.0         106
385.0          85
386.0          83
387.0          78
388.0          85
389.0         101
390.0          88
391.0         114
392.0          91
393.0          93
394.0          88
395.0         106
396.0          97
397.0          83
398.0          98
399.0          84
400.0          95
401.0          90
402.0          87
403.0          83
404.0          71
405.0          95
406.0         100
407.0          97
408.0          95
409.0          93
410.0          88
411.0          85
412.0          82
413.0          77
414.0          76
415.0          87
416.0          89
417.0          85
418.0          85
419.0          73
420.0          95
421.0         111
422.0          66
423.0          88
424.0          90
425.0          83
426.0          85
427.0          83
428.0          99
429.0          89
430.0          80
431.0          83
432.0          92
433.0          80
434.0          74
435.0          97
436.0          84
437.0          92
438.0          75
439.0          75
440.0          91
441.0          66
442.0          73
443.0          67
444.0          78
445.0          80
446.0          64
447.0          85
448.0          87
449.0          69
450.0          80
451.0          89
452.0          76
453.0          80
454.0          64
455.0          79
456.0          80
457.0          68
458.0          95
459.0          82
460.0          68
461.0          77
462.0          68
463.0          71
464.0          85
465.0          69
466.0          71
467.0          61
468.0          84
469.0          70
470.0          80
471.0          77
472.0          70
473.0          78
474.0          77
475.0          72
476.0          84
477.0          75
478.0          69
479.0          72
480.0          77
481.0          67
482.0          76
483.0          71
484.0          69
485.0          71
486.0          79
487.0          81
488.0          78
489.0          79
490.0          59
491.0          62
492.0          76
493.0          67
494.0          73
495.0          70
496.0          58
497.0          65
498.0          75
499.0          72
500.0          71
501.0          68
502.0          79
503.0          67
504.0          83
505.0          66
506.0          56
507.0          75
508.0          61
509.0          60
510.0          65
511.0          67
512.0          68
513.0          62
514.0          68
515.0          60
516.0          68
517.0          70
518.0          63
519.0          58
520.0          50
521.0          50
522.0          68
523.0          63
524.0          52
525.0          56
526.0          59
527.0          66
528.0          59
529.0          51
530.0          60
531.0          56
532.0          68
533.0          66
534.0          81
535.0          52
536.0          66
537.0          57
538.0          48
539.0          47
540.0          61
541.0          58
542.0          58
543.0          65
544.0          75
545.0          61
546.0          63
547.0          62
548.0          70
549.0          48
550.0          64
551.0          48
552.0          60
553.0          59
554.0          47
555.0          55
556.0          58
557.0          50
558.0          66
559.0          55
560.0          64
561.0          65
562.0          56
563.0          52
564.0          55
565.0          48
566.0          51
567.0          53
568.0          52
569.0          58
570.0          48
571.0          44
572.0          48
573.0          49
574.0          47
575.0          49
576.0          57
577.0          57
578.0          70
579.0          46
580.0          50
581.0          48
582.0          53
583.0          48
584.0          41
585.0          50
586.0          50
587.0          48
588.0          41
589.0          64
590.0          62
591.0          47
592.0          46
593.0          58
594.0          49
595.0          55
596.0          60
597.0          48
598.0          49
599.0          54
600.0          55
601.0          49
602.0          70
603.0          43
604.0          51
605.0          45
606.0          45
607.0          57
608.0          63
609.0          47
610.0          58
611.0          54
612.0          45
613.0          39
614.0          56
615.0          44
616.0          48
617.0          59
618.0          45
619.0          54
620.0          49
621.0          50
622.0          49
623.0          43
624.0          54
625.0          52
626.0          47
627.0          48
628.0          52
629.0          56
630.0          51
631.0          58
632.0          51
633.0          58
634.0          50
635.0          62
636.0          57
637.0          45
638.0          31
639.0          50
640.0          58
641.0          43
642.0          44
643.0          50
644.0          55
645.0          40
646.0          49
647.0          54
648.0          37
649.0          46
650.0          58
651.0          50
652.0          47
653.0          38
654.0          46
655.0          39
656.0          51
657.0          52
658.0          50
659.0          48
660.0          40
661.0          51
662.0          49
663.0          49
664.0          49
665.0          41
666.0          38
667.0          45
668.0          52
669.0          37
670.0          48
671.0          37
672.0          43
673.0          44
674.0          52
675.0          55
676.0          54
677.0          42
678.0          39
679.0          50
680.0          40
681.0          44
682.0          40
683.0          49
684.0          39
685.0          51
686.0          40
687.0          45
688.0          32
689.0          39
690.0          43
691.0          43
692.0          56
693.0          43
694.0          38
695.0          45
696.0          49
697.0          53
698.0          42
699.0          46
700.0          27
701.0          44
702.0          38
703.0          44
704.0          35
705.0          44
706.0          47
707.0          47
708.0          41
709.0          39
710.0          49
711.0          42
712.0          46
713.0          47
714.0          35
715.0          41
716.0          36
717.0          38
718.0          40
719.0          49
720.0          33
721.0          35
722.0          39
723.0          42
724.0          43
725.0          30
726.0          36
727.0          24
728.0          29
729.0          40
730.0          42
731.0          41
732.0          45
733.0          36
734.0          34
735.0          48
736.0          37
737.0          35
738.0          48
739.0          37
740.0          42
741.0          41
742.0          42
743.0          47
744.0          42
745.0          43
746.0          32
747.0          42
748.0          37
749.0          35
750.0          40
751.0          44
752.0          28
753.0          38
754.0          32
755.0          43
756.0          27
757.0          50
758.0          40
759.0          34
760.0          36
761.0          35
762.0          34
763.0          51
764.0          39
765.0          41
766.0          35
767.0          30
768.0          36
769.0          31
770.0          44
771.0          38
772.0          28
773.0          33
774.0          36
775.0          31
776.0          35
777.0          39
778.0          39
779.0          40
780.0          41
781.0          36
782.0          36
783.0          38
784.0          34
785.0          30
786.0          40
787.0          35
788.0          29
789.0          29
790.0          31
791.0          36
792.0          36
793.0          33
794.0          35
795.0          30
796.0          38
797.0          30
798.0          33
799.0          37
800.0          30
801.0          29
802.0          39
803.0          31
804.0          35
805.0          28
806.0          33
807.0          31
808.0          33
809.0          33
810.0          43
811.0          37
812.0          29
813.0          30
814.0          29
815.0          43
816.0          28
817.0          29
818.0          45
819.0          30
820.0          38
821.0          29
822.0          45
823.0          37
824.0          26
825.0          35
826.0          36
827.0          36
828.0          35
829.0          26
830.0          26
831.0          37
832.0          31
833.0          40
834.0          33
835.0          28
836.0          26
837.0          35
838.0          28
839.0          32
840.0          37
841.0          28
842.0          29
843.0          25
844.0          34
845.0          27
846.0          31
847.0          21
848.0          33
849.0          29
850.0          27
851.0          33
852.0          27
853.0          27
854.0          32
855.0          21
856.0          37
857.0          36
858.0          31
859.0          37
860.0          33
861.0          34
862.0          26
863.0          38
864.0          25
865.0          29
866.0          31
867.0          32
868.0          29
869.0          38
870.0          20
871.0          28
872.0          28
873.0          37
874.0          29
875.0          29
876.0          41
877.0          29
878.0          30
879.0          34
880.0          24
881.0          22
882.0          20
883.0          30
884.0          21
885.0          33
886.0          17
887.0          27
888.0          33
889.0          25
890.0          36
891.0          30
892.0          26
893.0          27
894.0          30
895.0          27
896.0          25
897.0          26
898.0          28
899.0          24
900.0          33
901.0          41
902.0          28
903.0          30
904.0          34
905.0          25
906.0          32
907.0          17
908.0          21
909.0          35
910.0          31
911.0          30
912.0          34
913.0          30
914.0          27
915.0          28
916.0          22
917.0          30
918.0          18
919.0          27
920.0          26
921.0          34
922.0          22
923.0          32
924.0          24
925.0          23
926.0          24
927.0          29
928.0          27
929.0          25
930.0          34
931.0          27
932.0          27
933.0          33
934.0          28
935.0          23
936.0          37
937.0          34
938.0          31
939.0          19
940.0          22
941.0          30
942.0          26
943.0          22
944.0          32
945.0          26
946.0          27
947.0          33
948.0          29
949.0          28
950.0          32
951.0          21
952.0          25
953.0          28
954.0          21
955.0          26
956.0          29
957.0          24
958.0          29
959.0          23
960.0          21
961.0          26
962.0          20
963.0          28
964.0          32
965.0          21
966.0          28
967.0          17
968.0          23
969.0          27
970.0          19
971.0          30
972.0          21
973.0          27
974.0          30
975.0          23
976.0          27
977.0          17
978.0          27
979.0          28
980.0          37
981.0          23
982.0          18
983.0          24
984.0          32
985.0          23
986.0          32
987.0          31
988.0          32
989.0          31
990.0          26
991.0          28
992.0          23
993.0          26
994.0          24
995.0          28
996.0          24
997.0          22
998.0          22
999.0          32
1000.0         23
1001.0         15
1002.0         24
1003.0         23
1004.0         24
1005.0         26
1006.0         31
1007.0         38
1008.0         27
1009.0         24
1010.0         31
1011.0         32
1012.0         25
1013.0         16
1014.0         23
1015.0         26
1016.0         32
1017.0         28
1018.0         23
1019.0         18
1020.0         30
1021.0         28
1022.0         30
1023.0         21
1024.0         30
1025.0         23
1026.0         24
1027.0         23
1028.0         22
1029.0         28
1030.0         13
1031.0         23
1032.0         19
1033.0         20
1034.0         25
1035.0         25
1036.0         25
1037.0         16
1038.0         25
1039.0         29
1040.0         21
1041.0         21
1042.0         25
1043.0         23
1044.0         33
1045.0         29
1046.0         17
1047.0         17
1048.0         27
1049.0         29
1050.0         18
1051.0         31
1052.0         24
1053.0         29
1054.0         18
1055.0         17
1056.0         28
1057.0         19
1058.0         22
1059.0         18
1060.0         24
1061.0         26
1062.0         19
1063.0         31
1064.0         19
1065.0         29
1066.0         31
1067.0         29
1068.0         17
1069.0         20
1070.0         29
1071.0         23
1072.0         20
1073.0         21
1074.0         17
1075.0         21
1076.0         22
1077.0         20
1078.0         31
1079.0         27
1080.0         25
1081.0         19
1082.0         23
1083.0         27
1084.0         27
1085.0         22
1086.0         18
1087.0         22
1088.0         26
1089.0         25
1090.0         28
1091.0         24
1092.0         14
1093.0         23
1094.0         22
1095.0         20
1096.0         20
1097.0         32
1098.0         20
1099.0         30
1100.0         28
1101.0         21
1102.0         21
1103.0         16
1104.0         16
1105.0         23
1106.0         25
1107.0         15
1108.0         22
1109.0         10
1110.0         23

In [169]:
# n~ 컬럼
n_cols = ['nplay_video', 'nevents', 'ndays_act', 'nchapters']
pre[n_cols] = pre[n_cols].fillna(0)
# 근거 : nplay_video, 0이 존재하지 않고, '시청시간이 없는 값'이 모두 NaN 처리가 되었다는 논리적 근거 O
# 데이터 상 결측이 존재하나 값 중 0이 존재하지 않고 / 시스템 상에서 활동이 없는 경우(의미적 0)를 NaN으로 남긴 것이다.
# 따라서 본 데이터 분석에서는 NaN를 '활동하지 않음'(=0)으로 간주하여 분석을 진행하였다.

In [170]:
# 110531 <<< 제거대상 
pre = pre.drop(pre[(pre['viewed'] == 0) & ((pre['nchapters'] > 0) | (pre['nevents'] > 0))].index)

In [171]:
# 논리적 이상치
    # nchapters값이 1인데 nan값으로 입력되었을 리 X ∴ 이상치
    # nplay_video의 기준이 클릭/완강인지 명시 X, 
    # But viewed 컬럼이 따로 존재하는 것으로 nplay_video가 완강 기준일 것이라는 근거로 분석을 진행했다.
    # nplay_video가 완강 기준일 것이라는 근거로 분석을 진행했다.
nonono = (pre['viewed'] == 0) & ((pre['nchapters'] > 0) | (pre['nevents'] > 0))

In [172]:
# start_time_DI (결측 71.36) -> 대신 ndays_act 이용하기?
# 음수가 나오는 애들 제거 후 한계점 감안하고 사용하라는 튜터님 피드백 있었음

In [173]:
# 아니면 ndays_act를 이용하는 방법 (몇일 이상 접속한 사람으로 구간 나눠서?) -> 그 기준은?
# 조사 필요할 듯
# ndays_act를 가지고 몇일 이상 접속해야 찍먹러가 아닌 기준에 대해서 명확하게 하고 싶은데

In [174]:
# 찍먹과 학습의지 수강생을 나눌 수 있을까?

ac_df = df[df['viewed'] == 1].copy()
viewed_rate = (df['viewed'] == 1).mean() * 100
viewed_rate # 62.42

np.float64(62.429929281995456)

In [175]:
# 파생컬럼 생성

# 학생들의 나이(age)
pre['age'] = pre['start_time_DI'].dt.year - pre['YoB']

# YoB 결측치를 0으로 채우기
pre['YoB'] = pre['YoB'].fillna(0)

# 최소 가입 나이 (13세)
pre.loc[pre['age'] < 13, 'age']

# 퍼널 단계 컬럼(step): 각 학생 별 진행 단계
pre['step'] = np.select(
    [
        pre['certified'] ==1,
        pre['explored'] == 1,
        pre['viewed'] == 1,
        pre['registered'] == 1,
    ],
    [
        'Certified',
        'Explored',
        'Viewed',
        'Registered'
    ],
    default='None'
)

In [176]:
# Unknown
un_cols = ['gender', 'LoE_DI', 'YoB']
pre[un_cols] = pre[un_cols].fillna('Unknown')

In [177]:
pre['age'].describe()

count    299277.000000
mean         27.279991
std           8.893779
min           0.000000
25%          21.000000
50%          25.000000
75%          30.000000
max          82.000000
Name: age, dtype: float64

In [178]:
# 퍼널 분석을 위한 탐색
    # 결국 우리 분석 대상은
    # 이탈자 / 반복학습생이 아닐까?
    # '끝까지 수료할 가능성'이 있는 사람들은 끌어모으고 << 잠재고객? 가치 파악? 수익성 ↑?
    # '이탈할 가능성' = 리스크는 줄이는 게 맞으니까 << 사실 이게 더 중요하긴 함 : 놓친 사람
    
# 이탈 이유가 결국 수강 의지가 있는 부류 / 없는데 이탈하는 부류 < 이 문제점을 파악해야
# 등록 - 첫수강에서 막히는지(진입 or 환경) / 수강 - 유지에서 막히는지(난이도)
# 찍먹러인지 중도포기인지 반복학습자? 인지
# 근데 이탈하면 어디서 많이 이탈하는지가 중요 -> 그래서 우리가 퍼널 별 구간 이탈자 탐색 < 이걸 하는거고 음음 굿

# 찍먹러는 ndays_act가 적은 사람으로 판단 가능? < 조사 필요
# 중도포기는 certified로 잡고 싶었는데 상당수가 수료 못해서 분류 기준이 비상이고
#

In [179]:
### 파생변수 아이디어

# 찍먹러
pre['out_cus'] = (pre['ndays_act'] <= 3)

pre['out_cus'].value_counts(normalize=True) * 100
# 2일 기준
# 찍먹러 54.87
# 논찍먹러 45.12

# 왜 이렇게 많지요...??
# 온라인이라 그냥 일단 신청하고 보자 일까

# 음 3일은 64 / 35
# 4일은 70 / 29

# 구간별로 잘라서 ~일로 열정수강생이랑 찍먹러랑 일반수강생이랑 나누고 싶은데 나누는 기준은 무엇으로?
# 이것도 추가 조사 필요함 근데 일단 찍어보니까 찍먹러는 3일 기준이 낫지 않을까 싶음 

# 코스 별로도 다를 테고, 페이지 클릭 횟수/완강 여부랑 같이 봐도 좋을 것 같음 (월요일에 추가조사+나눠서 보기 진행하면 어떨까)

out_cus
True     64.457347
False    35.542653
Name: proportion, dtype: float64

In [180]:
# 추가 조사 필요한 부분 조사
# 데이터 딕셔너리 업데이트
# 피드백 정리(문튜터님/제연튜터님)

###